### ISSUE TITLE
Not enough 'A'

### ISSUE THREAD

**Issue by xryshirfxn** [GazeAtStars/AAAAAAAAAAAAAAAAAAAAA#2]
I believe, it should be 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA' instead of 'AAAAAAAAAAAAAAAAAAAAA'

**Comment by ZeroTasteGuy** [comment]
Yeah, it's just not enough...

**Comment by Rstar284** [comment]
Fixed.
